cmake_minimum_required(VERSION 3.6.0)

# LAMA specific stuff
set(STM_PLATFORM ANDROID)
set(STM_PLATFORM_NAME "android")
set(STM_ANDROID 1)
set(STM_POSIX 1)
set(STM_ANDROID_COMPILER_FLAGS)
set(STM_ANDROID_COMPILER_FLAGS_CXX)
set(STM_ANDROID_COMPILER_FLAGS_C)